Merge branch 'bump-chef-zero' into 'master'
Bump chef-zero to 4.7.0 to retain Ruby 2.1 compatibility

https://github.com/chef/chef-zero/pull/219

The release builds were failing:

```
               [Builder: chef-zero] I | gem `install chef-zero --version '4.5.0' --bindir '/opt/gitlab/embedded/bin' --no-ri --no-rdoc': 39.2814s
               [Builder: chef-zero] I | Build chef-zero: 39.2832s
The following shell command exited with status 1:

    $ CFLAGS=-I/opt/gitlab/embedded/include -O2 CPPFLAGS=-I/opt/gitlab/embedded/include -O2 CXXFLAGS=-I/opt/gitlab/embedded/include -O2 LDFLAGS=-Wl,-rpath,/opt/gitlab/embedded/lib -L/opt/gitlab/embedded/lib LD_RUN_PATH=/opt/gitlab/embedded/lib PATH=/opt/gitlab/bin:/opt/gitlab/embedded/bin:/root/gems/ruby/2.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PKG_CONFIG_PATH=/opt/gitlab/embedded/lib/pkgconfig /opt/gitlab/embedded/bin/gem install chef-zero --version '4.5.0' --bindir '/opt/gitlab/embedded/bin' --no-ri --no-rdoc

Output:

    (nothing)

Error:

    ERROR:  Error installing chef-zero:
	rack requires Ruby version >= 2.2.2.
```

See merge request !852